# Generated by Django 4.2.1 on 2023-10-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('drillTitle', models.CharField(max_length=100, null=True)),
                ('totalTime', models.CharField(max_length=100, null=True)),
                ('totalDistance', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('dtMin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('zone4', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('zone5', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('zone6', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('hsr', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('hsrMin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('maxSpeed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('spints', models.IntegerField(null=True)),
                ('sprintDistance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('accelerations', models.IntegerField(null=True)),
                ('decelerations', models.IntegerField(null=True)),
                ('accMin', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('decMin', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('hmlDistance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('idPlayer', models.CharField(max_length=20)),
                ('idFile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file')),
            ],
        ),
    ]
