# Generated by Django 4.2.1 on 2023-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='u19', max_length=20),
            preserve_default=False,
        ),
    ]
