# Generated by Django 4.2.1 on 2023-06-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_session_alter_player_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='idPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='session',
            name='idFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
    ]
