# Generated by Django 4.2.1 on 2024-01-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
            preserve_default=False,
        ),
    ]
