# Generated by Django 4.2.1 on 2023-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_session_distance_session_accmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hsrMin',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='maxSpeed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
