# Generated by Django 4.2.1 on 2023-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_session_hsrmin_alter_session_maxspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ref',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
