# Generated by Django 4.2.1 on 2023-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_ref_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='accelerations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='decelerations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='idPlayer',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='spints',
            field=models.IntegerField(null=True),
        ),
    ]
